### ISSUE TITLE
rate limiting

### ISSUE THREAD

**Issue by MshadDr** [Safemood/REAL-TIME-LARAVEL-9-SOKETI#1]
how to prevent our soketi from DDOS attack,

could you show in a practical way with your awesome code.

**Comment by Safemood** [comment]
Hey there 😀

Typically, it's beyond coding. 😅

Soketi has a rate-limiting functionality 

Check docs

[Broadcast Rate Limiting](https://docs.soketi.app/rate-limiting-and-limits/broadcast-rate-limiting)

[Events & Channels Limits
](https://docs.soketi.app/rate-limiting-and-limits/events-and-channels-limits)

If you wanna customize them you can pass them to the docker container as an environment variable  "-e RATE_LIMITER_DRIVER='local'"

or you can deploy your server to Cloudflare with [Soketi Serverless](https://soketi.app) is still in beta, but it's very promising.

**Comment by MshadDr** [comment]
thank you khalil
